MODULE LegalEntity;

CLASS LegalEntity 'Организация';

name 'Наименование' = DATA STRING[100](LegalEntity) IN base;
address 'Адрес' = DATA STRING[150](LegalEntity) IN base;
inn 'ИНН' = DATA BPSTRING[9](LegalEntity) IN base;

legalEntityINN = GROUP AGGR LegalEntity legalEntity BY inn(legalEntity);

FORM legalEntities 'Организации'
    OBJECTS l = LegalEntity
    PROPERTIES(l) name, inn, address, NEW, DELETE
;
