MODULE Stock;

CLASS Stock 'Склад';

name 'Наименование' = DATA STRING[100] (Stock) IN base;
address 'Адрес' = DATA STRING[150] (Stock) IN base;

FORM stocks 'Склады'
    OBJECTS s = Stock
    PROPERTIES(s) READONLY name, address, NEW, EDIT, DELETE
    
    LIST Stock OBJECT s
;


FORM stock 'Склад'
    OBJECTS s = Stock PANEL 
    PROPERTIES(s) name, address, NEW, DELETE
    
    EDIT Stock OBJECT s
;